# 文档自动化管理配置文件

document_structure:
  # 必需章节列表
  required_sections:
    - "摘要"
    - "目录"
    - "理论基础"
    - "技术实现"
    - "实践应用"
    - "最佳实践"
    - "总结"
  
  # 最小章节数量
  min_sections: 5
  
  # 最小代码示例数量
  min_code_examples: 2
  
  # 是否要求目录
  require_toc: true
  
  # 是否要求摘要
  require_abstract: true

quality_checks:
  # 最小字数
  min_word_count: 500
  
  # 最大行长度
  max_line_length: 120
  
  # 是否要求代码块有语言标识
  require_code_language: true
  
  # 是否检查链接
  check_links: true

format_rules:
  # 是否修复标题格式
  fix_headers: true
  
  # 是否修复列表格式
  fix_lists: true
  
  # 是否修复代码块格式
  fix_code_blocks: true
  
  # 是否修复间距
  fix_spacing: true

file_patterns:
  # 包含的文件模式
  include:
    - "*.md"
  
  # 排除的目录模式
  exclude:
    - "node_modules/**"
    - ".git/**"
    - "tools/**"
    - "venv/**"
    - "__pycache__/**"

validation_rules:
  # 标题格式规则
  header_format: "^#{1,6}\\s+.+$"
  
  # 列表格式规则
  list_format: "^\\s*[-*+]\\s+.+$"
  
  # 代码块格式规则
  code_block_format: "^```\\w*\\n.*?```$"
  
  # 链接格式规则
  link_format: "\\[([^\\]]+)\\]\\(([^)]+)\\)"

report_settings:
  # 报告输出目录
  output_dir: "tools/reports"
  
  # 报告文件名格式
  filename_format: "quality_report_%Y%m%d_%H%M%S.md"
  
  # 是否包含详细结果
  include_details: true
  
  # 是否包含统计图表
  include_charts: false

automation_settings:
  # 自动修复设置
  auto_fix:
    enabled: true
    backup_original: true
    backup_dir: "tools/backups"
  
  # 批量处理设置
  batch_processing:
    max_concurrent: 4
    timeout: 30
  
  # 通知设置
  notifications:
    enabled: false
    email: ""
    webhook: ""

# 自定义规则
custom_rules:
  # 项目特定规则
  project_specific:
    - "必须包含版本信息"
    - "必须包含创建日期"
    - "必须包含作者信息"
  
  # 技术文档规则
  technical_docs:
    - "必须包含架构图"
    - "必须包含代码示例"
    - "必须包含配置示例"
  
  # 分析文档规则
  analysis_docs:
    - "必须包含数据图表"
    - "必须包含结论"
    - "必须包含建议"